### ISSUE TITLE
beta 2 and newrelic

### ISSUE THREAD

**Issue by burningTyger** [sinatra/sinatra#1186]
Ran into an issue today:

```ruby
  configure :production do
    newrelic_ignore '/ping'
  end
```

Error:

```
=== puma startup: 2016-09-22 11:56:19 +0200 ===
/home/user/.gem/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/sinatra/ignorer.rb:44:in `block in set_newrelic_ignore': undefined method `first' for #<Mustermann::Sinatra:"/ping"> (NoMethodError)
        from /home/user/.gem/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/sinatra/ignorer.rb:41:in `map'
        from /home/user/.gem/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/sinatra/ignorer.rb:41:in `set_newrelic_ignore'
        from /home/user/.gem/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/sinatra/ignorer.rb:20:in `newrelic_ignore'
        from /home/user/sv/sv.rb:33:in `block in <class:SV>'
        from /home/user/.gem/ruby/2.3.0/gems/sinatra-2.0.0.beta2/lib/sinatra/base.rb:1440:in `configure'
        from /home/user/sv/sv.rb:32:in `<class:SV>'
        from /home/user/sv/sv.rb:23:in `<top (required)>'
        from /home/user/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/sv/config.ru:1:in `block in <main>'
        from /home/user/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
        from /home/user/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
        from /home/user/sv/config.ru:in `new'
        from /home/user/sv/config.ru:in `<main>'
        from /home/user/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
        from /home/user/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
        from /home/user/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
        from /home/user/.gem/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
        from /home/user/.gem/ruby/2.3.0/bin/puma:23:in `load'
        from /home/user/.gem/ruby/2.3.0/bin/puma:23:in `<main>'
```

Sent an email to newrelic with the same message since they don't have an issue tracker.

**Comment by zzak** [comment]
I think this is a bug in Newrelic's thing, could you open a (support) ticket there?

**Comment by burningTyger** [comment]
I did. Unless it's something we can fix here I'll close the issue and update as appropriate.

**Comment by zzak** [comment]
@burningTyger Thank you! :bow: :bow: :bow:

**Comment by burningTyger** [comment]
Today's update: 

> we [newrelic] just released a [new version of the Ruby agent.](https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-3172327)
> 
> The new agent version features instrumentation for the Sinatra 2 beta.

I haven't yet tested it.
