### ISSUE TITLE
NoMethodError: undefined method `clear' for nil:NilClass

### ISSUE THREAD

**Issue by j4zzcat** [sinatra/sinatra#1263]
I'm getting the following exception by simply curling to my decode_token get method. 
Strangely enough, doing the exact same thing under rspec **does** work.
Puzzling situation.

```
NoMethodError: undefined method `clear' for nil:NilClass
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:903:in `call!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/bundle/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
        /usr/local/bundle/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
        /usr/local/bundle/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
        /usr/local/bundle/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/bundle/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
        /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
        /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
        /usr/local/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

**Comment by mwpastore** [comment]
Your Tilt::Cache is uninitialized for some reason. Can you show us more of how your application is configured and what your route does? Ideally distilled into a simple reproducible test case.
