### ISSUE TITLE
non utf-8 encoding issue with error handlers

### ISSUE THREAD

**Issue by eguzki** [sinatra/sinatra#1350]
Sinatra 2.0.0

When post request has a json body with non utf-8 encoding characters in keys, Sinatra middleware returns 400 with the following body:
> Invalid query parameters: invalid byte sequence in UTF-8

Request body example:
`
{                                          
  "\xf0\x90\x28\xbc": 3
}
`

Our Sinatra app has been configured to enable raise_errors and disable show_exceptions 
```
enable :raise_errors
disable :show_exceptions
```

We would like to customize error message, so we registered a BadRequest error handler:

```
error Sinatra::BadRequest do
  [400, {}, ['some error message']]               
end 
```

This error handling causes Sinatra app to raise exception internally. After a bit of debugging, crash happens @ https://github.com/sinatra/sinatra/blob/5de64980e0f0fe146d8b60ca3b009f183113e68b/lib/sinatra/base.rb#L1030

I guess "@params" is nil because due to encoding issue "@params" was not properly initialized @ https://github.com/sinatra/sinatra/blob/5de64980e0f0fe146d8b60ca3b009f183113e68b/lib/sinatra/base.rb#L1089

Calling "params" method of request object raises exception which is handled but "@params" is left uninitialized.

**Comment by jkowens** [comment]
Can you post a sample app that demonstrates this issue? I'd like to see how you are loading the JSON body into the params.

**Comment by eguzki** [comment]
Some steps to reproduce the issue were missing. Fair enough.

1.- Generate POST request body:
```
$ irb
2.2.4 :001 > File.open("body", 'w') { |file| file.write("{ \"\xf0\x90\x28\xbc\": 3 }") }
```
2.- App code without BadRequest error handler registered
```
$ cat myapp.rb
require 'sinatra'

post '/' do
  'Hello world!'
end
```
3.- Send request
```
$ curl -v -X POST -d @body http://localhost:4567
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: http://localhost:4567/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4567 (#0)
> POST / HTTP/1.1
> Host: localhost:4567
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 400 Bad Request 
< Content-Type: text/html;charset=utf-8
< Content-Length: 56
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Server: WEBrick/1.3.1 (Ruby/2.2.4/2015-12-16)
< Date: Mon, 02 Oct 2017 16:41:54 GMT
< Connection: Keep-Alive
< 
* Connection #0 to host localhost left intact
Invalid query parameters: invalid byte sequence in UTF-8
```
4.- App code BadRequest error handler registered
```$ cat myapp.rb 
require 'sinatra'

error Sinatra::BadRequest do
  [400, {}, ['some error message']]
end

post '/' do
  'Hello world!'
end
```
5.- Send request
```
$ curl -d @body http://localhost:4567
NoMethodError: undefined method `[]=' for nil:NilClass
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1030:in `process_route'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1148:in `block in error_block!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1145:in `reverse_each'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1145:in `error_block!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1134:in `handle_exception!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1097:in `rescue in dispatch!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1104:in `dispatch!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
	/home/eguzki/.rvm/gems/ruby-2.2.4@puma/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by jkowens** [comment]
Thanks for the additional details. I've submitted a PR that should resolve this issue.

**Comment by olleolleolle** [comment]
@namusyaka Can we put this one in 2.0.1, like #1351?

**Comment by namusyaka** [comment]
@olleolleolle Yeah, I'm going to merge the patch into v2.0.1, but it's the core part so I'm planning to review the PR carefully.
