### ISSUE TITLE
Undefined method 'downcase' for nil:NilClass when Sinatra under high load

### ISSUE THREAD

**Issue by heavydawson** [sinatra/sinatra#1367]
While load testing my Sinatra application with JMeter, I found an issue whereby hitting the exact same URL over and over would cause the following error to appear in small percentage of requests. The URL being touched didn't change between requests and > 99% of requests succeed without issue:

```
Unexpected error while processing request: undefined method `downcase' for nil:NilClass
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1854:in `block (2 levels) in <class:Base>'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1148:in `block in error_block!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1145:in `reverse_each'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1145:in `error_block!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1134:in `handle_exception!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1097:in `rescue in dispatch!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1104:in `dispatch!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/UserDir/.rvm/gems/ruby-2.4.2@hansel/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
```
My Sinatra instance is configured to use Thin as the backing HTTP server
It was only under load that this behaviour appeared. The load tester was configured to hit a single endpoint. The matching Sinatra route was:

```
get "/api/#{API_VER}/:type/:ids" do
end
```
It appears that under heavy load there are circumstances where the request object isn't properly populated. I can't tell if this is a Sinatra or Thin issue.

**Comment by jkowens** [comment]
I suspect this would be a Thin issue. Can add the Rack::Lint middleware to your Sinatra app and run the test again? I think that will help us confirm if the Rack environment variable is set before Sinatra being processing the route.

**Comment by heavydawson** [comment]
Here you go:

```
Unexpected error while processing request: env missing required key REQUEST_METHOD
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/lint.rb:20:in `assert'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/lint.rb:259:in `block in check_env'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/lint.rb:258:in `each'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/lint.rb:258:in `check_env'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/lint.rb:43:in `_call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/Users/david.corley/.rvm/gems/ruby-2.4.2@hansel/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
```

**Comment by jkowens** [comment]
The Rack spec requires that request header to be set. I think it’s safe to say that this is probably a Thin issue.

**Comment by heavydawson** [comment]
Opened a corresponding issue in Thin, so will close this out.
