### ISSUE TITLE
params can't be used as keyword arguments

### ISSUE THREAD

**Issue by baelter** [sinatra/sinatra#1592]
We can't pass `params` hash and expect keyword args to be matched because of the current `IndifferentHash` implementation.

```ruby	
def a(a:, **); end
a(Hash[a: 1]) # => nil
a(Sinatra::IndifferentHash[a: 1]) # => ArgumentError (wrong number of arguments (given 1, expected 0; required keyword: a))
a(**Sinatra::IndifferentHash[a: 1]) # => TypeError (hash key "a" is not a Symbol)
```

Changing the `IndifferentHash` private method `convert_key` to always return `key.to_s.to_sym` solves this.

**Comment by jkowens** [comment]
This issue has also been brought up in the Rails project. Since this models ActiveSupport::HashWithIndifferentAccess I would like to stay in line with the approach there. I'm wondering if we can also provide a method `symbolize_keys` that will serve as a work around.

See:

rails/rails#14643

https://bugs.ruby-lang.org/issues/9731

https://til.hashrocket.com/posts/d66e55091c-hashwithindifferentaccess-for-keyword-arguments

**Comment by baelter** [comment]
Okey, maybe it can be done as an opt-in setting. I'll look into that.

**Comment by dentarg** [comment]
> Changing the `IndifferentHash` private method `convert_key` to always return `key.to_s.to_sym` solves this.

That has this downside:

```
$ ruby -rsinatra/base -e 'module Sinatra;class IndifferentHash;def convert_key(key);key.to_s.to_sym;end;end;end; ih=Sinatra::IndifferentHash.new; pp ih.merge({ "\xAB" => "a" })'
-e:1:in `to_sym': invalid symbol in encoding UTF-8 :"\xAB" (EncodingError)
	from -e:1:in `convert_key'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/sinatra-4.0.0/lib/sinatra/indifferent_hash.rb:131:in `block (2 levels) in merge!'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/sinatra-4.0.0/lib/sinatra/indifferent_hash.rb:130:in `each_pair'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/sinatra-4.0.0/lib/sinatra/indifferent_hash.rb:130:in `block in merge!'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/sinatra-4.0.0/lib/sinatra/indifferent_hash.rb:126:in `each'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/sinatra-4.0.0/lib/sinatra/indifferent_hash.rb:126:in `merge!'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/sinatra-4.0.0/lib/sinatra/indifferent_hash.rb:144:in `merge'
	from -e:1:in `<main>'
```

```
$ ruby -rsinatra/base -e 'ih=Sinatra::IndifferentHash.new; pp ih.merge({ "\xAB" => "a" })'
{"\xAB"=>"a"}
```
