### ISSUE TITLE
Helpers loaded but not found in registered(app)

### ISSUE THREAD

**Issue by adisciple50** [sinatra/sinatra#1597]
Ive included the helper in the app file. ive tried everything I could think of and I think It could be a problem with Sinatra. I know it simply includes the module, but ive tried include statements in client_report.rb and app.rb. ive tried it with and without relative_require  '/helpers/models'. nothing is shifting it. please help. thanks.

## /helpers/models.rb

```
# frozen_string_literal: true

module Archcare
  module Logbook
    module Helpers
      module Models
        # Saves typing it out again!
        def access_db(document_type)
          Archcare::Logbook::Helpers::Models::Access.new document_type
        end
        class Access
          def initialize(model)
            @model = model
          end

          def create_document(fields)
            # see House declaration for fields needed.
            document = @model.new fields
            document.save!
            document._id
          end

          #  get all document function - include ids
          def get_documents_where(criteria)
            # thankyou Jesus for the help with this one.
            if criteria.is_a? Hash
              alldocuments = @model.where(criteria).all
              if alldocuments.exists?
                return alldocuments
              else
                return false
              end
            else
              raise TypeError('Hash expected with where criteria.')
            end
          end

          # Get one document
          def get_document(id)
            document = @model.find(id)
            if document.exists?
              return document
            else
              return false
            end
          end

          # Get all documents
          def get_all_documents
            alldocuments = @model.all
            if alldocuments.exists?
              return alldocuments
            else
              return false
            end
          end

          # Update a document
          def update_document(id, fields)
            document = @model.find(id)
            if document.exists?
              document.update_attributes fields
            else
              false
            end
          end

          # delete document
          def delete_document(id)
            document = @model.find(id)
            if is_admin?
              document.delete
            else
              false
            end
          end
          puts "Models is loaded"
        end
      end
    end
  end
end
```

## /routes/client_report.rb
```
module Archcare
  module Logbook
    module Routes
      module ClientReport

        require 'sinatra/base'
        require_relative '../model/client_report'
        require_relative '../model/client'
        require_relative '../helpers/cookies'
        require_relative '../helpers/authentication'
        require_relative '../helpers/clients'
        require_relative '../helpers/users'
        require_relative '../helpers/reports'
        # require_relative '../helpers/models'

        def self.registered(app)
          clients_db = access_db(Archcare::Logbook::Model::Client)
          clients_for_privilege_level = is_admin? ? clients_db.get_all_documents : get_clients_for_user(current_user_id)
          app.get '/client-report' do
            if logged_in?
              erb :creport,locals: {:title => "New Client Report" ,
                                    :cookie => has_agreed?,
                                    # get all clients from the database
                                    :clients => clients_for_privilege_level}
            elsif !logged_in?
              redirect '/login'
            end
            end
          app.post '/client-report/new' do
            if logged_in?
              user = get_current_user
              client_report = Archcare::Logbook::Model::ClientReport.new(
                                                                        {:date => params['date'],
                                                                         :report => params['report'],
                                                                         :clients => params['client'],
                                                                         :users => user._id,
                                                                         :creport_user_mentions => get_users_from_report(params['report']),
                                                                         :creport_client_mentions => get_clients_from_report(params['report']),
                                                                         :hashtags => get_or_create_hashtags(params['report'])
                                                                        }
              )
              client_report.save!
              redirect '/client-report'
            elsif !logged_in?
              redirect '/login'
            end
          end
          # redirect helper function
          app.get '/client-report/view' do
            redirect '/client-report/' + params['id'] + '/view'
          end
          app.get '/client-report/:id/view' do
            erb ':viewcreport', locals: {:title => "View Client Report" ,:cookie => has_agreed?,:id => params['id']}
          end
        end
      end
    end
  end
end

`
## /app.rb

`# frozen_string_literal: true

module Archcare
  module Logbook
    # https://docs.mongodb.com/mongoid/master/tutorials/getting-started-sinatra/
    require 'sinatra/base'
    require 'mongoid'
    require 'sysrandom'
    require 'rack/session/encrypted_cookie'

    require_relative 'helpers/authentication'
    require_relative 'helpers/cookies'
    require_relative 'helpers/clients'
    require_relative 'helpers/users'
    require_relative 'helpers/reports'
    require_relative 'helpers/models'
    require_relative 'helpers/rendering'

    require_relative 'routes/authentication'
    require_relative 'routes/home'
    require_relative 'routes/onboarding'
    require_relative 'routes/cookies'
    require_relative 'routes/client_report'
    require_relative 'routes/clients'
    require_relative 'routes/houses'
    require_relative 'routes/reports'

    COOKIE_SECRET = SecureRandom.hex(64).to_s
    # The main app
    class Logbook < Sinatra::Base
      use Rack::Protection::RemoteToken
      use Rack::Protection::SessionHijacking
      configure do
        enable :sessions
        set :session_secret, COOKIE_SECRET
      end

      Mongoid.load!(File.join(File.dirname(__FILE__), 'config', 'mongoid.yml'))

      helpers Archcare::Logbook::Helpers::Authentication
      helpers Archcare::Logbook::Helpers::Cookies
      helpers Archcare::Logbook::Helpers::Clients
      helpers Archcare::Logbook::Helpers::Users
      helpers Archcare::Logbook::Helpers::Reports
      helpers Archcare::Logbook::Helpers::Rendering
      helpers Archcare::Logbook::Helpers::Models


      register Archcare::Logbook::Routes::Authentication
      register Archcare::Logbook::Routes::ClientReport
      register Archcare::Logbook::Routes::Home
      register Archcare::Logbook::Routes::Onboarding
      register Archcare::Logbook::Routes::Cookies
      register Archcare::Logbook::Routes::Clients
      register Archcare::Logbook::Routes::Houses
      register Archcare::Logbook::Routes::Reports

      run!
    end
  end
end
```

## Error Output

```
C:\Ruby26-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/Jason/source/ArchcareLogbook/app.rb
Models is loaded
C:/Users/Jason/source/ArchcareLogbook/routes/client_report.rb:18:in `registered': undefined method `access_db' for Archcare::Logbook::Routes::ClientReport:Module (NoMethodError)
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1415:in `block in register'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1413:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1413:in `register'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:50:in `<class:Logbook>'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:30:in `<module:Logbook>'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:4:in `<module:Archcare>'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:3:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

**Comment by adisciple50** [comment]
changing the helper module to Sinatra::Models namespace does nothing either.

> `C:\Ruby26-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/Jason/source/ArchcareLogbook/app.rb
Models is loaded
C:/Users/Jason/source/ArchcareLogbook/routes/client_report.rb:18:in `registered': undefined method `access_db' for Archcare::Logbook::Routes::ClientReport:Module (NoMethodError)
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1415:in `block in register'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1413:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1413:in `register'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:51:in `<class:Logbook>'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:30:in `<module:Logbook>'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:4:in `<module:Archcare>'
	from C:/Users/Jason/source/ArchcareLogbook/app.rb:3:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
`

**Comment by adisciple50** [comment]
apon further investigation of whether any of my helper functions are loading concluded that they werent. I removed references to this troublesome module and immediately the next helper module was failed to be recognised. im wondering if is_admin? loaded in any other extensions that were declared before client report.

**Comment by adisciple50** [comment]
is_admin? is not called in the authentication routes.
```
      register Archcare::Logbook::Routes::Authentication
      register Archcare::Logbook::Routes::ClientReport
```
whats going on?

**Comment by adisciple50** [comment]
> is_admin? is not called in the authentication routes.
but logged_in? (which is from the same helper module) is called the Authentication Extension. so the module is being read but for some reason, the function from the same module is not reconised.

**Comment by adisciple50** [comment]
case solved.
look at client_report.rb

```
 def self.registered(app)
          clients_db = access_db(Archcare::Logbook::Model::Client)
          clients_for_privilege_level = is_admin? ? clients_db.get_all_documents : get_clients_for_user(current_user_id)
          app.get '/client-report' do
            if logged_in?
```

variables assigned outside of a route! i havent seen this as a rule in any writing extension guides so put the word out . so thankyou Jesus for answering my prayer and leading me down the right path.
prayer helps when your stuck in anything!
im refactoring and commiting on my project now :)
