### ISSUE TITLE
Custom error handler not called if exception happens in before

### ISSUE THREAD

**Issue by mscrivo** [sinatra/sinatra#1660]
With sinatra 2.1.0, I have an error handler setup in my controller base like this:

```ruby
error do
  # render custom 500 page
end
```

which works fine for picking up unhandled exceptions in any endpoints. However, I also have a `before` filter defined in the same controller base class and if an exception happens in there, let's say the a database connection fails, it doesn't get routed through my custom handler, instead it goes into the base Sinatra `error ::Exception` and I get the default "Internal Server Error" page.

Is this expected? I would think exceptions that happen in `before` should also get handled by the custom error handler?

Thanks!

**Comment by froderik** [comment]
I managed to recreate this problem with a test. I don't understand the code well enough to fix it though. A workaround for you would be to pass in 500 or a range of error codes even and then the before filter will work as intended.

```ruby
error 400..510 do
  # render custom 500 page
end
```

And for reference here is the test I added to `filter_test.rb`:

```ruby
  it 'can catch exceptions in before filter and handle them propertly' do
    doodle = ''
    mock_app do
      before do
        doodle = 'before'
        raise StandardError, "before"
      end
      error do
        "Error handled #{env['sinatra.error'].message}"
      end
      get "/" do
        doodle += "now"
      end
    end

    get '/'
    assert_equal 'Error handled before', body
    assert_equal 'before', doodle
  end
```

This breaks and adding any param that includes 500 to the error makes it work. Same problem is true for the `after` filter.

**Comment by bolpin** [comment]
I have a possible fix at https://github.com/bolpin/sinatra/tree/handle-unspecified-before-filter-errors

**Comment by dentarg** [comment]
I'm not seeing this, am I missing something?

Starting app with `bundle exec puma -p 5000 -e production`

### `Gemfile`

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 2.2"
gem "puma", "~> 5.6"
```

### `config.ru`

````ruby
# frozen_string_literal: true

$stdout.sync = true
$stderr.sync = true

Bundler.require

class BeforeApp < Sinatra::Base
  before do
    raise "Error in before"
  end

  get "/" do
    body "OK"
  end

  error do
    puts "puts from error block in BeforeApp"

    "body from error block in BeforeApp"
  end
end

class App < Sinatra::Base
  get "/" do
    raise "Error in route"
    body "OK"
  end

  error do
    puts "puts from error block in App"

    "body from error block in App"
  end
end


map "/before" do
  run BeforeApp
end

map "/" do
  run App
end
````

### Requests

````bash
$ curl -s -v localhost:5000/
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 28
<
* Connection #0 to host localhost left intact
body from error block in App


$ curl -s -v localhost:5000/before
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /before HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 34
<
* Connection #0 to host localhost left intact
body from error block in BeforeApp
````

<Details><Summary>App logs</Summary>

````
Puma starting in single mode...
* Puma version: 5.6.2 (ruby 3.0.3-p157) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 95390
* Listening on http://0.0.0.0:5000
Use Ctrl-C to stop
2022-03-15 08:44:47 - RuntimeError - Error in route:
  config.ru:26:in `block in <class:App>'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/xss_header.rb:18:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/json_csrf.rb:26:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/frame_options.rb:31:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/configuration.rb:252:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/request.rb:77:in `block in handle_request'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/request.rb:76:in `handle_request'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/server.rb:441:in `process_client'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
puts from error block in App
2022-03-15 08:44:52 - RuntimeError - Error in before:
  config.ru:10:in `block in <class:BeforeApp>'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1010:in `block in filter!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1009:in `each'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1009:in `filter!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1137:in `block in dispatch!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/xss_header.rb:18:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/json_csrf.rb:26:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-protection-2.2.0/lib/rack/protection/frame_options.rb:31:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'
  /Users/dentarg/.gem/ruby/3.0.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
  /Users/dentarg/.gem/ruby/3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/configuration.rb:252:in `call'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/request.rb:77:in `block in handle_request'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/request.rb:76:in `handle_request'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/server.rb:441:in `process_client'
  /Users/dentarg/.gem/ruby/3.0.3/gems/puma-5.6.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
puts from error block in BeforeApp
````

</Details>

**Comment by dentarg** [comment]
Not seeing it with Sinatra 2.1.0 either

**Comment by bolpin** [comment]
The discrepancy I saw was between:
``` ruby
require 'sinatra'

set :environment, :test
before do
  raise "error in before"
end

get "/" do
  body "OK"
end

error 500 do
  body "ERROR Body"
end
```

and 
```ruby
# ...

error do
  body "ERROR Body"
end
```
Probably not a big deal.  Feel free to close the MR.  Thanks for taking a look.
