### ISSUE TITLE
Unable to require 'sinatra/custom_logger' after install sinatra-contrib

### ISSUE THREAD

**Issue by doublechiang** [sinatra/sinatra#1675]
Apology if this is not the right place to ask a question here. Please let me know if it's not appropriate.

I read the document http://sinatrarb.com/contrib/custom_logger
Follow the instructions install gem with
`gem install sinatra-contrib`
After installation 

```
$ gem list --local | grep contrib
sinatra-contrib (2.1.0)
```
And in my source, just require them
`
require 'sinatra/base'
require 'sinatra/custom_logger'
require 'logger'
`
when I executed it, it still show LoadError
`
require': cannot load such file -- sinatra/custom_logger (LoadError)`

None of the extensions can be loaded, but sinatra/base can be loaded. Do I miss something?

**Comment by horaciob** [comment]
Are you working with Gemfile and running `bundle exec?`

if you do remember to add `gem 'sinatra-contrib'` into your Gemfile and then start.

**Comment by doublechiang** [comment]
Thansk for the reply. Yes, I had done it.
Also executed
``` bundle update
```

**Comment by froderik** [comment]
I tried it and it works for me. On ruby 2.4 I first installed sinatra-contrib with 

```
gem install sinatra-contrib
```

And then I fired up `irb`:

```
irb(main):001:0> require 'sinatra'
=> true
irb(main):002:0> require 'sinatra/custom_logger'
=> true
```

You (@doublechiang) probably need to add more information about your environment in order to get help. :smiley:

**Comment by doublechiang** [comment]
Appreciated the response.
The problem is where should I look at? Can you let me know where to digging into it?

**Comment by froderik** [comment]
So if you do the exact thing I did is that not working for you? Then I would say your ruby set up is completely broken. Reinstalling it perhaps would work. Other questions that comes to mind is: what versions of ruby, gem and bundler are you on? Are you using something like `rvm` or `rbenv` to switch between flavors of ruby?

**Comment by epergo** [comment]
@doublechiang Could you provide us with a sample application? Also the information that @froderik requested could come handy too

**Comment by doublechiang** [comment]
If I used irb, then it work.
```
test@qctus-cchiang:/mnt/c/works/lab_systems$ irb
irb(main):001:0> require 'sinatra/base'
=> true
irb(main):002:0> require 'sinatra/custom_logger'
=> true
irb(main):003:0>
```

However, in my 'config.ru' file
```
require 'sinatra/base'
require 'sinatra/custom_logger'
Dir.glob('./{lib,controllers}/*.rb').each { |file| require file }
....
```

Then start this by command line
```
APP_ENV=development bundle exec rackup config.ru -I /mnt/c/works/lab_systems -I /mnt/c/works/lab_systems/lib -p 4567

11:46:36 [rerun] Lab_systems launched
11:46:36 [rerun] Rerun (20387) running Lab_systems (20396)
Traceback (most recent call last):
        15: from /usr/local/bin/rackup:23:in `<main>'
        14: from /usr/local/bin/rackup:23:in `load'
        13: from /var/lib/gems/2.5.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
        12: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
        11: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        10: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
         9: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
         8: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
         7: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
         6: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
         5: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
         4: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
         3: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
         2: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
         1: from /mnt/c/works/lab_systems/config.ru:2:in `block in <main>'
/mnt/c/works/lab_systems/config.ru:2:in `require': cannot load such file -- sinatra/custom_logger (LoadError)
```

And the version I had also I did not use any of rvm or rbenv.
```
test@qctus-cchiang:/mnt/c/works/lab_systems$ ruby --version
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
test@qctus-cchiang:/mnt/c/works/lab_systems$ gem --version
2.7.6.2
test@qctus-cchiang:/mnt/c/works/lab_systems$ bundler --version
Bundler version 1.17.3
test@qctus-cchiang:/mnt/c/works/lab_systems$ rvm
-bash: rvm: command not found
test@qctus-cchiang:/mnt/c/works/lab_systems$ rbenv
-bash: rbenv: command not found
test@qctus-cchiang:/mnt/c/works/lab_systems$
```

When I reported this issue, I was using MAC, now switch to WSL, and still get the same error. So strange.

**Comment by froderik** [comment]
You are running sinatra with bundler. Nice! This means that the dependencies would be in a file called `Gemfile` - maybe you can post the content of that file? Also `Gemfile.lock` is of interest - it is generated when you run `bundle install`.

As a side note it is likely that it will work if you remove `bundle exec` from the command that starts sinatra. But then your dependencies will not be nicely managed with your code so not recommended.

**Comment by doublechiang** [comment]
very appreciate your time on this.
My Gemfile
```
# use 'bundle install' to instll the required gem

source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'rerun'
gem 'session'
gem 'rake'
gem 'sqlite3'
gem 'sinatra-activerecord'
gem 'activerecord', '~> 5.2'
gem 'will_paginate'

group :development, :test do
  gem 'rspec'
  gem 'rack-test'
  gem "rspec-html-matchers"
end
```

Gemfile is a bit lengthy, so attached as  a file.
[Gemfile.lock.txt](https://github.com/sinatra/sinatra/files/6052964/Gemfile.lock.txt)

**Comment by epergo** [comment]
To be able to require `sinatra/custom_logger` you need to add `sinatra-contrib` to your Gemfile.

```ruby
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib' # <--- Add this
gem 'thin'
gem 'rerun'
gem 'session'
gem 'rake'
gem 'sqlite3'
gem 'sinatra-activerecord'
gem 'activerecord', '~> 5.2'
gem 'will_paginate'

group :development, :test do
  gem 'rspec'
  gem 'rack-test'
  gem "rspec-html-matchers"
end
```

Inside `irb` it worked because you installed it manually through `gem install sinatra-contrib`

**Comment by doublechiang** [comment]
Thanks for the help.
I added `gem 'siantra-contrib' into the Gemfile, re-run the bundle install.
It was listed in the output message.
However, it still shows the error message when I started the application.

```
test@qctus-cchiang:/mnt/c/works/lab_systems$ bundle install
Using rake 13.0.3
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.5.0
  /var/lib/gems/2.5.0/build_info
  /var/lib/gems/2.5.0/cache
  /var/lib/gems/2.5.0/doc
  /var/lib/gems/2.5.0/extensions
  /var/lib/gems/2.5.0/gems
  /var/lib/gems/2.5.0/specifications
Using concurrent-ruby 1.1.8
Using i18n 1.8.9
Using minitest 5.14.4
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 5.2.4.5
Using activemodel 5.2.4.5
Using arel 9.0.0
Using activerecord 5.2.4.5
Using bundler 1.17.3
Using daemons 1.3.1
Using diff-lcs 1.4.4
Using eventmachine 1.2.7
Using ffi 1.14.2
Using rb-fsevent 0.10.4
Using rb-inotify 0.10.1
Using listen 3.4.1
Using mini_portile2 2.5.0
Using multi_json 1.12.1
Using ruby2_keywords 0.0.4
Using mustermann 1.1.1
Using racc 1.5.2
Using nokogiri 1.11.1 (x86_64-linux)
Using rack 2.2.3
Using rack-protection 2.1.0
Using rack-test 1.1.0
Using rerun 0.13.1
Using rspec-support 3.10.2
Using rspec-core 3.10.1
Using rspec-expectations 3.10.1
Using rspec-mocks 3.10.2
Using rspec 3.10.0
Using rspec-html-matchers 0.9.4
Using session 3.2.0
Using tilt 2.0.10
Using sinatra 2.1.0
Using sinatra-activerecord 2.0.22
Using sinatra-contrib 2.1.0
Using sqlite3 1.4.2
Using thin 1.8.0
Using will_paginate 3.3.0
Bundle complete! 13 Gemfile dependencies, 42 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
Error message 
```
APP_ENV=development bundle exec rackup config.ru -I /mnt/c/works/lab_systems -I /mnt/c/works/lab_systems/lib -p 4567

15:53:41 [rerun] Lab_systems launched
15:53:41 [rerun] Rerun (20778) running Lab_systems (20787)
Traceback (most recent call last):
        15: from /usr/local/bin/rackup:23:in `<main>'
        14: from /usr/local/bin/rackup:23:in `load'
        13: from /var/lib/gems/2.5.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
        12: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
        11: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        10: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
         9: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
         8: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
         7: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
         6: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
         5: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
         4: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
         3: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
         2: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
         1: from /mnt/c/works/lab_systems/config.ru:2:in `block in <main>'
/mnt/c/works/lab_systems/config.ru:2:in `require': cannot load such file -- sinatra/custom_logging (LoadError)

15:53:43 [rerun] Lab_systems Launch Failed
```

**Comment by froderik** [comment]
Hmm you misspelled sinatra-contrib in the post here. But maybe it is correct in the Gemfile? Otherwise I don't know - I don't think that you should need the `-I` flags to rackup but I can't see that it would hurt either.

**Comment by doublechiang** [comment]
@froderik Ah! yes, I misspelled the 'sinatra-contrib' in the post. but it's corrected spelled in the Gemfile. The error message can see it is correctly spelled in my error log.
It seems so simple and I just don't get how it can't be loaded. And it happened on 2 of my systems, WSL on Windows and MAC OSx.

**Comment by froderik** [comment]
Perhaps - as epergo suggested - you can set up an empty repo that recreates the issue and share with us. It will be easier to solve the issue then!

**Comment by epergo** [comment]
@doublechiang in the last error trace I see the following:

```bash
/mnt/c/works/lab_systems/config.ru:2:in `require': cannot load such file -- sinatra/custom_logging (LoadError)
```

`sinatra/custom_logging` is not correct, should be `sinatra/custom_logger` could you review it?

**Comment by doublechiang** [comment]
Ah! many thanks. It is! After correcting the typo, it works now. Thank you all for my silly question. I am terribly sorry for the simple typo problem bothering me so long, I just didn't catch it...;-(
Thank you all for your kindly help.
