### ISSUE TITLE
Getting 500 EOFError when malformed multipart/form-data POST request arrives

### ISSUE THREAD

**Issue by tamazon** [sinatra/sinatra#1739]
Sinatra crashes when malformed POST request arrives by EOFError. The POST request has "Content-Type: form/multi-part" header, but does not have any content in its body.
It should be handled and return 400 (Bad Request) instead of 500.

# How to reproduce this Error
1. make sinatra app just like GETTING STARTED and install sinatra(2.1.0)
2. start local server with `ruby myapp.rb`
3. send a malformed POST request with curl (has multipart/form-data header without content)
  `curl -v -X POST -H 'Content-Type: multipart/form-data; boundary=dummy' http://localhost:4567/post-end-point`
4. Sinatra returns `HTTP/1.1 500 Internal Server Error`
<details>
<summary>Click to Open Error log</summary>

```
EOFError: EOFError
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart/parser.rb:359:in `handle_empty_content!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart/parser.rb:186:in `on_read'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart/parser.rb:73:in `parse'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart.rb:54:in `extract_multipart'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:594:in `parse_multipart'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:446:in `POST'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:469:in `params'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:32:in `params'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:78:in `params'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1118:in `dispatch!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/logger.rb:17:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:253:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:246:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

```

</details>

As a workaround, I applied a patch to Sinatra::Request#params to consider the error as a bad request:
```
# my patch
# frozen_string_literal: true

require "sinatra/base"

module Sinatra
  class Request
    def params
      super
    rescue Rack::Utils::ParameterTypeError, Rack::Utils::InvalidParameterError => e
      raise BadRequest, "Invalid query parameters: #{Rack::Utils.escape_html(e.message)}"
    rescue EOFError => e
      raise BadRequest, "Invalid multipart/form-data: #{Rack::Utils.escape_html(e.message)}"
    end
  end
end
```
I'll make a PR if you like it.

**Comment by jkowens** [comment]
If you would be willing to open a PR that would be great, thanks!

**Comment by tamazon** [comment]
Thank you for your reply. I'm going to write a PR for this issue.

**Comment by dentarg** [comment]
This is also a problem in `Rack::Protection::AuthenticityToken` which also does `Rack::Request.new(env).params`: https://github.com/sinatra/sinatra/blob/cf404526373298f06a59e1a129b6cdf8282ae216/rack-protection/lib/rack/protection/authenticity_token.rb#L113

Note that the `EOFError` will turn into `Rack::Multipart::EmptyContentError` once there's a rack release with https://github.com/rack/rack/pull/1688

**Comment by dentarg** [comment]
Some more context, the `EOFError` started happening after https://github.com/rack/rack/pull/1572

**Comment by dentarg** [comment]
I'm using a middleware like this in my apps

```ruby
class CheckParamsMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    # https://github.com/rack/rack/pull/1572 made rack raise EOFError on
    # malformed multipart/form-data POST requests when reading the params.
    # Trigger that early and stop the request before we reach Sinatra, to avoid
    # the need to add specific error handlers to all controllers.
    Rack::Request.new(env).params

    @app.call(env)
  rescue EOFError
    [400, {}, ["Bad Request"]]
  end
end
```

**Comment by tamazon** [comment]
@dentarg  I tried to write middleware like that but couldn't make it work.
It turns out that `Rack::Request.new(env).params` was the missing part from my code.

Thanks for much needed information!

**Comment by jkowens** [comment]
Would those exception classes need to be rescued here?

https://github.com/sinatra/sinatra/blob/e69b6b9dee7165d3a583fc8a6af10ceee1ea687d/lib/sinatra/base.rb#L77

I see Grape has a thread on fixing this issue: https://github.com/ruby-grape/grape/pull/2161

**Comment by tamazon** [comment]
@jkowens I think so. Grape looks like doing same thing.

Should I rescue `Rack::Multipart::EmptyContentError` as well for future-proofing?

**Comment by dentarg** [comment]
> Should I rescue `Rack::Multipart::EmptyContentError` as well for future-proofing?

You can't really do that as `EmptyContentError` doesn't exist in rack (https://github.com/rack/rack/commit/249dd785625f0cbe617d3144401de90ecf77025a hasn't been part of a release yet), but I noticed now that the new `EmptyContentError` inherits from `EOFError` so rescuing `EOFError` will rescue the new error:

```ruby
irb(main):001:0> class EmptyContentError < ::EOFError; end
=> nil
irb(main):002:1* begin
irb(main):003:1*   raise EmptyContentError
irb(main):004:1* rescue EOFError => e
irb(main):005:1*   puts "error rescued!"
irb(main):006:1*   puts e.inspect
irb(main):007:0> end
error rescued!
#<EmptyContentError: EmptyContentError>
=> nil
```

**Comment by tamazon** [comment]
@dentarg That's good to know. Thanks for your help again!
