### ISSUE TITLE
Get tests to pass on `truffleruby-22`

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1798]
Tracking issue to get CI green for truffleruby-22 (continuing https://github.com/sinatra/sinatra/pull/1751)

Current status: https://github.com/sinatra/sinatra/runs/7419870830?check_suite_focus=true#step:5:9

* sinatra tests FAIL
* sinatra-contrib tests PASS
* rack-protection tests PASS

Some `require_relative` failure

```
<internal:core> core/kernel.rb:293:in `require_relative': /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/nokogiri-1.13.7-x86_64-linux/lib/nokogiri/3.0/nokogiri.so: undefined symbol: rb_eTypeError (RuntimeError)
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/nokogiri-1.13.7-x86_64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from <internal:core> core/kernel.rb:2[9](https://github.com/sinatra/sinatra/runs/7419870830?check_suite_focus=true#step:5:10)3:in `require_relative'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/nokogiri-1.13.7-x86_64-linux/lib/nokogiri.rb:[10](https://github.com/sinatra/sinatra/runs/7419870830?check_suite_focus=true#step:5:11):in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/test/nokogiri_test.rb:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/rake-[13](https://github.com/sinatra/sinatra/runs/7419870830?check_suite_focus=true#step:5:14).0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.1.1/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
/home/runner/.rubies/truffleruby-[22](https://github.com/sinatra/sinatra/runs/7419870830?check_suite_focus=true#step:5:23).1.0/bin/bundle:[23](https://github.com/sinatra/sinatra/runs/7419870830?check_suite_focus=true#step:5:24):in `<main>'
```

**Comment by dentarg** [comment]
Any idea @eregon / @bjfish?

**Comment by eregon** [comment]
This sounds likely to be this Bundler bug: https://github.com/rubygems/rubygems/issues/5691
2.3.18 should have the fix though, but maybe the cache is causing the bug to remain here.
I'll try a run on my fork which won't have the cache to see if that's it.
Maybe I should bump the cache version in ruby/setup-ruby to avoid this problem.

Once that's solved, I think we should close this issue and focus on the truffleruby-head issue (https://github.com/sinatra/sinatra/issues/1799).

**Comment by eregon** [comment]
Actually that Bundler bug is still present at least in this form, I can reproduce locally with no cache whatsoever: https://github.com/rubygems/rubygems/issues/5691#issuecomment-1190019556

**Comment by eregon** [comment]
I think we can close this one, it's basically tracked by that Bundler issue.

**Comment by dentarg** [comment]
Thanks for investigating this!

**Comment by eregon** [comment]
Thanks for filing the issues, that was good motivation :)
