### ISSUE TITLE
Ensure integration tests runs with Puma

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1874]
> Tests output show `puma is not installed, skipping integration tests` so I think this _require_ is not working as expected.

_Originally posted by @epergo in https://github.com/sinatra/sinatra/pull/1858#discussion_r1103611324_

**Comment by dentarg** [comment]
So the reason for the change over at https://github.com/sinatra/sinatra/pull/1858/files/a8ec48da5861970a8dc97706d511093a00417ca7#diff-cb4a09a087ed85c2331c53261acfe2b38823d8acbdcaae0d0ec8cc7d499d04e9 (which is incorrect, should have been `rack/handler/puma`) was to battle this failure:

```
  1) Failure:
IntegrationTest#test_with_puma_starts_the_correct_server_1 [/app/test/integration_test.rb:52]:
Expected /
      ==\sSinatra\s\(v3.0.5\)\s
      has\staken\sthe\sstage\son\s\d+\sfor\sdevelopment\s
      with\sbackup\sfrom\s#<IntegrationHelper::BaseServer:0x0000aaaaf20a62a0>
    /ix to match "".
```

It happens because `server.log` is the empty (string) at

https://github.com/sinatra/sinatra/blob/72e5b33fcb71ebfb3f405ff4df7581f6b967323a/test/integration_test.rb#L50

when the async test runs 

https://github.com/sinatra/sinatra/blob/baa6bf783ea6dd8d2a708aa604c8ee583a90ee23/test/integration_async_helper.rb#L7

It is empty for rainbows too, but as seen above, the assertion isn't run for rainbows. However, that conditional makes it so the assertions isn't run for rainbows for the regular integration tests as well, so I don't like the idea of adding such conditional for puma.

**Comment by dentarg** [comment]
The reason for the log being empty seems to be this

```
IntegrationTest#test_with_puma_starts_the_correct_server_0 = log Exception e=Traceback (most recent call last):
	27: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:83:in `block in autorun'
	26: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:159:in `run'
	25: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:182:in `__run'
	24: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:182:in `map'
	23: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:182:in `block in __run'
	22: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:350:in `run'
	21: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:378:in `with_info_handler'
	20: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:391:in `on_signal'
	19: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:351:in `block in run'
	18: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:351:in `each'
	17: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:352:in `block (2 levels) in run'
	16: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:365:in `run_one_method'
	15: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:1051:in `run_one_method'
	14: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest/test.rb:95:in `run'
	13: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest/test.rb:247:in `with_info_handler'
	12: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:391:in `on_signal'
	11: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest/test.rb:96:in `block in run'
	10: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest.rb:296:in `time_it'
	 9: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest/test.rb:97:in `block (2 levels) in run'
	 8: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest/test.rb:199:in `capture_exceptions'
	 7: from /usr/local/bundle/gems/minitest-5.17.0/lib/minitest/test.rb:102:in `block (3 levels) in run'
	 6: from /app/test/integration_helper.rb:117:in `block (2 levels) in it'
	 5: from /app/test/integration_helper.rb:104:in `run_test'
	 4: from /app/test/integration_helper.rb:104:in `instance_eval'
	 3: from /app/test/integration_test.rb:49:in `block in <class:IntegrationTest>'
	 2: from /app/sinatra-contrib/lib/sinatra/runner.rb:96:in `log'
	 1: from /app/sinatra-contrib/lib/sinatra/runner.rb:96:in `loop'
/app/sinatra-contrib/lib/sinatra/runner.rb:96:in `block in log': undefined method `read_nonblock' for nil:NilClass (NoMethodError)
server.log=""
```

(the above output came from logging the `#full_message` of the exception at https://github.com/sinatra/sinatra/blob/72e5b33fcb71ebfb3f405ff4df7581f6b967323a/sinatra-contrib/lib/sinatra/runner.rb#L91-L96)

**Comment by dentarg** [comment]
No problem when running only async tests (`bundle exec ruby test/integration_async_test.rb --verbose`)

**Comment by dentarg** [comment]
> No problem when running only async tests (`bundle exec ruby test/integration_async_test.rb --verbose`)

Or only `test/integration_test.rb`

Running `TESTOPTS="--name='/starts_the_correct_server/'" bundle exec rake` triggers it

**Comment by dentarg** [comment]
So the regular integration tests starts all servers before running the tests: https://github.com/sinatra/sinatra/blob/f10e571f4d9d670ec7992b7a122cae6780ce5474/test/integration_helper.rb#L128-L143

but for the async tests, the servers are started much later, during `run_test`, the `run` call in https://github.com/sinatra/sinatra/blob/f10e571f4d9d670ec7992b7a122cae6780ce5474/test/integration_helper.rb#L107-L117
