### ISSUE TITLE
Remove code for encrypted cookies in favour of rack-session

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1945]
### Discussed in https://github.com/sinatra/sinatra/discussions/1878

<div type='discussions-op-text'>

<sup>Originally posted by **dentarg** February 18, 2023</sup>
Is https://github.com/sinatra/sinatra/pull/1324 and https://github.com/rack/rack/pull/1805 (started as https://github.com/rack/rack/pull/1177) (now living in https://github.com/rack/rack-session) the same?</div>

<div type='discussions-op-text'>

<sup>Originally posted by **jkowens** February 19, 2023</sup>
@dentarg yep that’s what I got from those threads.</div>

<div type='discussions-op-text'>

<sup>Originally posted by **dentarg** February 19, 2023</sup>
Seeing they are the same, is it wise to have them duplicated going forward?

I guess what I'm asking is if the code in Sinatra should be dropped in favor of the rack-session code</div>

<div type='discussions-op-text'>

<sup>Originally posted by **jkowens** February 19, 2023</sup>
Ohh yes. Yes we should definitely drop that now that we can.</div>

**Comment by dentarg** [comment]
I'm hesitant about doing this for Sinatra 4. After taking a closer looking I've realised the implementations are similar but not the same. This can be seen in [my `decode_rack_cookie` script](https://github.com/dentarg/gists/blob/master/gists/decode_rack_cookie) ([permalink](https://github.com/dentarg/gists/blob/28803470ca0c37d721fde29d4379587c000555b9/gists/decode_rack_cookie)).

There's also this difference https://github.com/rack/rack-session/issues/29 between rack-protection and rack-session >=2.

Lastly https://github.com/rack/rack-session/pull/23 was merged into rack-session adding yet more differences (but probably brought good benefits) but it hasn't been released yet.

**Comment by dentarg** [comment]
I looked/[played](https://github.com/dentarg/gists/commit/339c956dc3706481a5307e94d3cfd12e5c7fdcc1) with https://github.com/rack/rack-session/pull/23 rack-session main and understand it a bit more now.

It probably makes a lot of sense to remove `Rack::Protection::EncryptedCookie` for sinatra/rack-protection 4 as it will give users access to `Rack::Session::Cookie` from the rack-session gem anyway due to https://github.com/sinatra/sinatra/blob/fa5a1399b6b63bcca2df81db284ff64a89a2b599/rack-protection/rack-protection.gemspec#L44

**Comment by dentarg** [comment]
Just as a fun exercise, with `Rack::Protection::EncryptedCookie = Rack::Session::Cookie` in `encrypted_cookie_spec.rb` (after removing ` Rack::Protection::{EncryptedCookie,Encryptor}`) then running those tests produced this results:

<details><summary>Details</summary>
<p>


```ruby
root@ccb9f4a67776:/app/rack-protection# bundle e rspec ./spec/lib/rack/protection/encrypted_cookie_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 19004

Rack::Session::Cookie
  loads from a cookie with integrity hash
  barks on too big cookies
  allows for non-strict encoded cookie
  allows passing in a hash with session data from middleware in front
  supports either of secret or old_secret
  ignores tampered with session cookies (FAILED - 1)
  ignores tampered with legacy hmac cookie
  exposes :coder in env['rack.session.option']
  doesn't warn if coder is configured to handle encoding
  warns if secret is to short (FAILED - 2)
  destroys session
  can handle Rack::Lint middleware
  warns if no secret is given
  does not return a cookie if cookie was not read/written
  returns the session id in the session hash
  exposes correct :coder when a secret is used
  returns no cookie if no data was written and no session was created previously, even if :expire_after is set
  loads from a cookie
  loads from a legacy hmac cookie
  supports custom digest class for legacy hmac cookie (FAILED - 3)
  allows more than one '--' in the cookie when calculating legacy digests
  survives broken cookies
  loads from a cookie with accept-only integrity hash for graceful key rotation (FAILED - 4)
  does not return a cookie if set to secure but not using ssl
  still warns if coder is not set
  uses a coder (FAILED - 5)
  can handle middleware that inspects the env
  does not return a cookie if cookie was not written (only read)
  creates a new cookie
  returns even if not read/written if :expire_after is set
  exposes :secret in env['rack.session.option']
  allows modifying session data with session data from middleware in front
  renew session id
  Base64
    handles non-strict base64 encoding
    uses base64 to decode
    uses base64 to encode
    Marshal
      marshals and base64 decodes
      marshals and base64 encodes
      rescues failures on decode
    ZipJSON
      jsons, deflates, and base64 encodes
      base64 decodes, inflates, and decodes json
      rescues failures on decode
    JSON
      JSON and base64 encodes
      rescues failures on decode
      JSON and base64 decodes

Failures:

  1) Rack::Session::Cookie ignores tampered with session cookies
     Failure/Error: tampered_with_cookie = [ctxt, iv, auth_tag.reverse].join('--')

     NoMethodError:
       undefined method `reverse' for nil:NilClass
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:352:in `block (2 levels) in <top (required)>'

  2) Rack::Session::Cookie warns if secret is to short
     Failure/Error: Rack::Protection::EncryptedCookie.new(incrementor, secret: secret[0, 16])

     ArgumentError:
       invalid secret: 16, must be >=64
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/encryptor.rb:55:in `initialize'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:170:in `new'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:170:in `block in initialize'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:169:in `map'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:169:in `initialize'
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:185:in `new'
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:185:in `block (2 levels) in <top (required)>'

  3) Rack::Session::Cookie supports custom digest class for legacy hmac cookie
     Failure/Error: env['rack.session']['counter'] ||= 0

     TypeError:
       wrong argument type Class (expected OpenSSL/Digest)
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:289:in `legacy_generate_hmac'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:285:in `legacy_digest_match?'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:235:in `block in unpacked_cookie_data'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/request.rb:107:in `fetch'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/request.rb:107:in `fetch_header'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:214:in `unpacked_cookie_data'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/cookie.rb:210:in `extract_session_id'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:76:in `id'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:335:in `current_session_id'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:341:in `session_exists?'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:162:in `exists?'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:187:in `load_for_read!'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:89:in `[]'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:470:in `[]'
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:8:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:272:in `context'
     # /usr/local/bundle/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:266:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/lint.rb:63:in `response'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/lint.rb:35:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/mock_request.rb:81:in `request'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/mock_request.rb:54:in `get'
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:74:in `response_for'
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:397:in `block (2 levels) in <top (required)>'

  4) Rack::Session::Cookie loads from a cookie with accept-only integrity hash for graceful key rotation
     Failure/Error: expect(response.body).to eq('{"counter"=>2}')

       expected: "{\"counter\"=>2}"
            got: "{\"counter\"=>1}"

       (compared using ==)
     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:322:in `block (2 levels) in <top (required)>'

  5) Rack::Session::Cookie uses a coder
     Failure/Error: expect(identity.calls).to eq(%i[decode encode])

       expected: [:decode, :encode]
            got: [:encode]

       (compared using ==)

       Diff:
       @@ -1 +1 @@
       -[:decode, :encode]
       +[:encode]

     # ./spec/lib/rack/protection/encrypted_cookie_spec.rb:229:in `block (2 levels) in <top (required)>'

Top 5 slowest examples (0.03282 seconds, 69.8% of total time):
  Rack::Session::Cookie loads from a cookie with accept-only integrity hash for graceful key rotation
    0.01955 seconds ./spec/lib/rack/protection/encrypted_cookie_spec.rb:315
  Rack::Session::Cookie loads from a cookie with integrity hash
    0.00547 seconds ./spec/lib/rack/protection/encrypted_cookie_spec.rb:299
  Rack::Session::Cookie uses a coder
    0.0037 seconds ./spec/lib/rack/protection/encrypted_cookie_spec.rb:207
  Rack::Session::Cookie loads from a cookie
    0.00243 seconds ./spec/lib/rack/protection/encrypted_cookie_spec.rb:238
  Rack::Session::Cookie returns no cookie if no data was written and no session was created previously, even if :expire_after is set
    0.00166 seconds ./spec/lib/rack/protection/encrypted_cookie_spec.rb:468

Finished in 0.04702 seconds (files took 0.14766 seconds to load)
45 examples, 5 failures

Failed examples:

rspec ./spec/lib/rack/protection/encrypted_cookie_spec.rb:343 # Rack::Session::Cookie ignores tampered with session cookies
rspec ./spec/lib/rack/protection/encrypted_cookie_spec.rb:184 # Rack::Session::Cookie warns if secret is to short
rspec ./spec/lib/rack/protection/encrypted_cookie_spec.rb:386 # Rack::Session::Cookie supports custom digest class for legacy hmac cookie
rspec ./spec/lib/rack/protection/encrypted_cookie_spec.rb:315 # Rack::Session::Cookie loads from a cookie with accept-only integrity hash for graceful key rotation
rspec ./spec/lib/rack/protection/encrypted_cookie_spec.rb:207 # Rack::Session::Cookie uses a coder

Randomized with seed 19004
```

</p>
</details>

**Comment by dentarg** [comment]
> Lastly [rack/rack-session#23](https://github.com/rack/rack-session/pull/23) was merged into rack-session adding yet more differences

Yeah, one more is JRuby incompatibility: https://github.com/jruby/jruby-openssl/issues/290 (can be seen at https://github.com/rack/rack-session/actions/runs/7393982068/job/20553984189?pr=28#step:4:18)

(For the record, Rails does not support JRuby: https://github.com/rails/rails/issues/49737#issuecomment-1783431477)

**Comment by jcmfernandes** [comment]
Hi there. I'm the author of https://github.com/rack/rack-session/pull/23 and I'm also to blame for the changes to Rails that caused the same issue. Shame on me, I'm sorry about that.

Regarding `rack-session`, I put up https://github.com/rack/rack-session/pull/32 to fix it. Regarding Rails, I see that the Rails team closed the reporting issue, but I'll try again to bring it to their attention.
