### ISSUE TITLE
Tests flaky on JRuby

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2027]
From https://github.com/sinatra/sinatra/actions/runs/9880366465/job/27288730224#step:5:26

`jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 11.0.23+9 on 11.0.23+9 +jit [x86_64-linux]`

```
  1) Error:
IntegrationTest#test_with_puma_logs_once_in_development_mode_0:
Net::HTTPBadResponse: wrong status line: "x-content-type-options: nosniff"
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/net/http/response.rb:43:in `read_status_line'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/net/http/response.rb:31:in `read_new'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/net/http.rb:1609:in `block in transport_request'
    org/jruby/RubyKernel.java:1423:in `catch'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/net/http.rb:1600:in `transport_request'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/net/http.rb:1573:in `request'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:333:in `block in open_http'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/net/http.rb:985:in `start'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:327:in `open_http'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:760:in `buffer_open'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:214:in `block in open_loop'
    org/jruby/RubyKernel.java:1423:in `catch'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:212:in `open_loop'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:153:in `open_uri'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:740:in `open'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/open-uri.rb:748:in `read'
    sinatra-contrib/lib/sinatra/runner.rb:153:in `get_url'
    sinatra-contrib/lib/sinatra/runner.rb:73:in `block in get'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/timeout.rb:189:in `block in timeout'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/timeout.rb:36:in `block in catch'
    org/jruby/RubyKernel.java:1423:in `catch'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/timeout.rb:36:in `catch'
    /home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/timeout.rb:198:in `timeout'
    sinatra-contrib/lib/sinatra/runner.rb:73:in `get'
    sinatra-contrib/lib/sinatra/runner.rb:128:in `block in alive?'
    org/jruby/RubyFixnum.java:306:in `times'
    sinatra-contrib/lib/sinatra/runner.rb:128:in `alive?'
    test/integration_helper.rb:108:in `run_test'
    test/integration_helper.rb:122:in `block in it'
```

but it passed in the previous round: https://github.com/sinatra/sinatra/actions/runs/9879363987/job/27285440086

**Comment by dentarg** [comment]
Test passed when the build was re-run. I will allow JRuby to fail for now, leaving this open as a reminder.

**Comment by dentarg** [comment]
jruby-head failed at https://github.com/sinatra/sinatra/actions/runs/11726432582/job/32665062599#step:5:28 but the jruby build had no problems

```
1) Error:
IntegrationTest#test_with_puma_sets_the_app_file_0:
Net::HTTPBadResponse: wrong status line: "content-type: text/html;charset=utf-8"
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/net/http/response.rb:43:in `read_status_line'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/net/http/response.rb:31:in `read_new'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/net/http.rb:1609:in `block in transport_request'
    org/jruby/RubyKernel.java:1426:in `catch'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/net/http.rb:1600:in `transport_request'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/net/http.rb:1573:in `request'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:333:in `block in open_http'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/net/http.rb:985:in `start'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:327:in `open_http'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:760:in `buffer_open'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:214:in `block in open_loop'
    org/jruby/RubyKernel.java:1426:in `catch'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:212:in `open_loop'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:153:in `open_uri'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:740:in `open'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/open-uri.rb:748:in `read'
    sinatra-contrib/lib/sinatra/runner.rb:153:in `get_url'
    sinatra-contrib/lib/sinatra/runner.rb:73:in `block in get'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/timeout.rb:189:in `block in timeout'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/timeout.rb:36:in `block in catch'
    org/jruby/RubyKernel.java:1426:in `catch'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/timeout.rb:36:in `catch'
    /home/runner/.rubies/jruby-head/lib/ruby/stdlib/timeout.rb:198:in `timeout'
    sinatra-contrib/lib/sinatra/runner.rb:73:in `get'
    sinatra-contrib/lib/sinatra/runner.rb:1[28](https://github.com/sinatra/sinatra/actions/runs/11726432582/job/32665062599#step:5:29):in `block in alive?'
    org/jruby/RubyFixnum.java:306:in `times'
    sinatra-contrib/lib/sinatra/runner.rb:128:in `alive?'
    test/integration_helper.rb:108:in `run_test'
    test/integration_helper.rb:122:in `block in it'
```

**Comment by dentarg** [comment]
jruby head worked fine here https://github.com/sinatra/sinatra/actions/runs/11936860840/job/33271496598

`jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-11-19 fe763ca666 OpenJDK 64-Bit Server VM 11.0.25+9 on 11.0.25+9 +jit [x86_64-linux]`
