### ISSUE TITLE
ruby-head failure

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2042]
Reported at https://github.com/puma/puma/pull/3485#issuecomment-2346732479

See log at https://github.com/MSP-Greg/sinatra/actions/runs/10834167576/job/30062684301#step:5:26

```
starting
[2024-09-12 15:40:50] INFO  WEBrick 1.8.1
[2024-09-12 15:40:50] INFO  ruby 3.4.0 (2024-09-09) [x86_64-linux]
== Sinatra (v4.0.0) has taken the stage on 5033 for development with backup from WEBrick
[20[24](https://github.com/MSP-Greg/sinatra/actions/runs/10834167576/job/30062684301#step:5:25)-09-12 15:40:50] INFO  WEBrick::HTTPServer#start: pid=2863 port=5033
[2024-09-12 15:40:51] ERROR bad URI `/ping'.
127.0.0.1 - - [12/Sep/2024:15:40:51 UTC] "GET /ping HTTP/1.1" 400 279
- -> /ping

...

- -> /ping
/home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:120:in 'block in Sinatra::Runner#ping': timeout starting server with command 'APP_ENV=development exec "/home/runner/.rubies/ruby-head/bin/ruby" -w -I "/home/runner/work/sinatra/sinatra/lib" "/home/runner/work/sinatra/sinatra/test/integration/app.rb" -s webrick -o 127.0.0.1 -p 5033 -e development 2>&1' (RuntimeError)
	from <internal:kernel>:191:in 'Kernel#loop'
	from /home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:115:in 'Sinatra::Runner#ping'
	from /home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:60:in 'Sinatra::Runner#run'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:50:in 'IntegrationHelper::BaseServer#run'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:25:in 'IntegrationHelper::BaseServer.run'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:139:in 'block in IntegrationHelper.extend_object'
	from <internal:array>:53:in 'Array#each'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:138:in 'Enumerable#each_with_index'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:138:in 'IntegrationHelper.extend_object'
	from /home/runner/work/sinatra/sinatra/test/integration_test.rb:9:in 'Kernel#extend'
	from /home/runner/work/sinatra/sinatra/test/integration_test.rb:9:in '<class:IntegrationTest>'
	from /home/runner/work/sinatra/sinatra/test/integration_test.rb:8:in '<top (required)>'
	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundled_gems.rb:79:in 'Kernel.require'
	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundled_gems.rb:79:in 'block (2 levels) in Kernel#replace_require'
	from -e:1:in '<main>'
rake aborted!
```

**Comment by dentarg** [comment]
ruby-head works fine: https://github.com/sinatra/sinatra/actions/runs/11719395781/job/32642568571

Tests with Puma head (and Ruby 3.2) works: https://github.com/sinatra/sinatra/actions/runs/11719395781/job/32642567208

The above error came from ruby-head + puma head in the same build, [testing](https://starkast.wiki/sinatra) with `rubylang/ruby:master-nightly-jammy` today, I had no problems.
