### ISSUE TITLE
Tests fail with `rackup` 2.2.0

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2055]
Probably related to the removal of `webrick` as a dependency: https://github.com/rack/rackup/pull/23

Example: https://github.com/dentarg/sinatra/actions/runs/11689259158/job/32551632501

```
/home/runner/work/sinatra/sinatra/vendor/bundle/ruby/2.7.0/gems/commonmarker-0.23.10/lib/commonmarker.rb:44: warning: mismatched indentations at 'end' with 'class' at 15
/home/runner/work/sinatra/sinatra/vendor/bundle/ruby/2.7.0/gems/commonmarker-0.23.10/lib/commonmarker/config.rb:52: warning: mismatched indentations at 'end' with 'class' at 36
/home/runner/work/sinatra/sinatra/vendor/bundle/ruby/2.7.0/gems/sass-embedded-1.63.6/ext/sass/embedded_sass_pb.rb:15: warning: assigned but unused variable - e
APP_ENV=development exec "/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/ruby" -w -I "/home/runner/work/sinatra/sinatra/lib" "/home/runner/work/sinatra/sinatra/test/integration/app.rb" -s falcon -o 127.0.0.1 -p 5021 -e development 2>&1
loading
starting
/home/runner/work/sinatra/sinatra/vendor/bundle/ruby/2.7.0/gems/rackup-2.2.0/lib/rackup/handler.rb:81:in `pick': Couldn't find handler for: falcon. (LoadError)
	from /home/runner/work/sinatra/sinatra/lib/sinatra/base.rb:1626:in `run!'
	from /home/runner/work/sinatra/sinatra/lib/sinatra/main.rb:47:in `block in <module:Sinatra>'
/home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:120:in `block in ping': timeout starting server with command 'APP_ENV=development exec "/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/ruby" -w -I "/home/runner/work/sinatra/sinatra/lib" "/home/runner/work/sinatra/sinatra/test/integration/app.rb" -s falcon -o 127.0.0.1 -p 5021 -e development 2>&1' (RuntimeError)
	from /home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:[11](https://github.com/dentarg/sinatra/actions/runs/11689259158/job/32551632501#step:5:12)5:in `loop'
	from /home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:115:in `ping'
	from /home/runner/work/sinatra/sinatra/sinatra-contrib/lib/sinatra/runner.rb:60:in `run'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:50:in `run'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:25:in `run'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:[13](https://github.com/dentarg/sinatra/actions/runs/11689259158/job/32551632501#step:5:14)9:in `block in extend_object'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:138:in `each'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:138:in `each_with_index'
	from /home/runner/work/sinatra/sinatra/test/integration_helper.rb:138:in `extend_object'
	from /home/runner/work/sinatra/sinatra/test/integration_test.rb:9:in `extend'
	from /home/runner/work/sinatra/sinatra/test/integration_test.rb:9:in `<class:IntegrationTest>'
	from /home/runner/work/sinatra/sinatra/test/integration_test.rb:8:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

**Comment by dentarg** [comment]
> Probably related to the removal of `webrick` as a dependency: [rack/rackup#23](https://github.com/rack/rackup/pull/23)

and that the Ruby 2.7 build uses this old Falcon version: https://rubygems.org/gems/falcon/versions/0.42.3 – I will exclude it from testing
