### ISSUE TITLE
500 `const_missing` `Rack::Files` in v4.1.1

### ISSUE THREAD

**Issue by yaauie** [sinatra/sinatra#2073]
I'm getting 500 responses from some requests in v4.1.1, notably:

`NameError`: `uninitialized constant Rack::Files` from [`lib/sinatra/base.rb:300`](https://github.com/sinatra/sinatra/blob/v4.1.1/lib/sinatra/base.rb#L300).

<details>
  <summary>Full Backtrace</summary>
  

```
org/jruby/RubyModule.java:4336:in `const_missing'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:300:in `body'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:1173:in `invoke'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:1188:in `dispatch!'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:1004:in `block in call!'
org/jruby/RubyKernel.java:1426:in `catch'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:1164:in `invoke'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:1004:in `call!'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:993:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/base.rb:53:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/xss_header.rb:20:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/path_traversal.rb:18:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/json_csrf.rb:28:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/base.rb:53:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/base.rb:53:in `call'
/${GEMDIR}/rack-protection-4.1.1/lib/rack/protection/frame_options.rb:33:in `call'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/middleware/logger.rb:17:in `call'
/${GEMDIR}/rack-3.1.8/lib/rack/head.rb:15:in `call'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:227:in `call'
/${GEMDIR}/sinatra-4.1.1/lib/sinatra/base.rb:2138:in `call'
/${GEMDIR}/rack-3.1.8/lib/rack/urlmap.rb:76:in `block in call'
org/jruby/RubyArray.java:1981:in `each'
/${GEMDIR}/rack-3.1.8/lib/rack/urlmap.rb:60:in `call'
/${APPDIR}/logstash-core/lib/logstash/api/rack_app.rb:75:in `call'
/${APPDIR}/logstash-core/lib/logstash/api/rack_app.rb:49:in `call'
/${GEMDIR}/rack-3.1.8/lib/rack/builder.rb:277:in `call'
/${GEMDIR}/puma-6.5.0-java/lib/puma/request.rb:99:in `block in handle_request'
/${GEMDIR}/puma-6.5.0-java/lib/puma/thread_pool.rb:389:in `with_force_shutdown'
/${GEMDIR}/puma-6.5.0-java/lib/puma/request.rb:98:in `handle_request'
/${GEMDIR}/puma-6.5.0-java/lib/puma/server.rb:468:in `process_client'
/${GEMDIR}/puma-6.5.0-java/lib/puma/server.rb:249:in `block in run'
/${GEMDIR}/puma-6.5.0-java/lib/puma/thread_pool.rb:166:in `block in spawn_thread'
```

</details>

I _believe_ it may have something to do with a [recent change to the `require` list, possibly that `Rack::Files` was previously _transitively_ loaded by `require "rack/session"`](https://github.com/sinatra/sinatra/commit/9c147640d0af8d5149d85814e2949cd06741e52f#diff-d91dacd5fa5ae6f9bf2a5597340fdc531421266ba821aa7a5739b941e5677fa9R11).

At some point the 500's go away, and I'm able to get 2xx responses.

**Comment by dentarg** [comment]
Which version of JRuby are you using?

It would be good to understand how the issue can be reproduced

**Comment by dentarg** [comment]
@yaauie can you give more info?

**Comment by dentarg** [comment]
Is this a JRuby autoload problem? Rack has `autoload :Files, "rack/files"`
https://github.com/rack/rack/blob/v3.1.8/lib/rack.rb#L31 so there's no need to require it manually for anyone.

Closing for now, but feel free to share more info here @yaauie if you have it.

**Comment by dentarg** [comment]
Maybe related to https://github.com/jruby/jruby/issues/6781
