### ISSUE TITLE
Classy error pages doesn't appear

### ISSUE THREAD

**Issue by nanolab** [sinatra/sinatra#963]
Sinatra 1.4.5
When I start this simple app with error:
```ruby
require 'sinatra'
get '/' do
  "Hello World!"
  aaaaa # Error here
end
```
ruby app.rb -o 0.0.0.0
I exect to see error page with error details, but I see this:
![](http://i.imgur.com/pLvBZW1.jpg)
And log:
```
NameError - undefined local variable or method `aaaaa' for #<Sinatra::Application:0x00000001f6a530>:
        app.rb:11:in `block in <main>'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /home/deploy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        /home/deploy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        /home/deploy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
[2015-01-21 16:07:09] ERROR NoMethodError: undefined method `join' for #<String:0x007f74804aab68>
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        /home/deploy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /home/deploy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        /home/deploy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        /home/deploy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

```

**Comment by kgrz** [comment]
This is similar to https://github.com/sinatra/sinatra/issues/951

The fix is already in master branch. Until a new release is made, you can point the gem to master:

```ruby
# Gemfile

gem 'sinatra', github: 'sinatra/sinatra'
```

**Comment by nanolab** [comment]
Great! It works.
Thank you.

**Comment by drewblas** [comment]
@kgrz Is there any information on when a release will be?  There hasn't been once since April.  It's very sad to have Sinatra broken by default

**Comment by epitron** [comment]
+1!

This doesn't need an entire sinatra release -- just a hotfix for 1.4.5. :)
